pipeline {
  agent any
  parameters {
    string(name: 'projectName', defaultValue: 'psapp', description: 'Project name to create or target for update')
  } 
  stages {
    stage('Database') {
      steps {
        build job: 'database', parameters: [[$class: 'StringParameterValue', name: 'projectName', value: projectName]]
        }
      }
    stage('DB Monitoring') {
      steps {
        build job: 'dbmon', parameters: [[$class: 'StringParameterValue', name: 'projectName', value: projectName]]
      }
    }
    stage('Petclinic') {
      steps {
        build job: 'petclinic', parameters: [[$class: 'StringParameterValue', name: 'projectName', value: projectName]]
      }
    }
    stage('Moodle') {
      steps {
        build job: 'moodle', parameters: [[$class: 'StringParameterValue', name: 'projectName', value: projectName]]
      }
    }
    stage('Prometheus') {
      steps {
        build job: 'prometheus', parameters: [[$class: 'StringParameterValue', name: 'projectName', value: projectName]]
      }
    }
    stage('Grafana') {
      steps {
        build job: 'grafana', parameters: [[$class: 'StringParameterValue', name: 'projectName', value: projectName]]
      }
    }
  }  
}
